onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - cn-font-split
  - esbuild
  - koffi
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
